#!/usr/bin/env bash

set -eu

usage() {
  cat <<EOF

Usage: kubectl forward-exec TYPE/NAME [options] [LOCAL_PORT:]REMOTE_PORT [...[LOCAL_PORT_N:]REMOTE_PORT_N] [-- <commands...>]

Forward one or more local ports to a pod, run a command on local machine and finally stop the port forward.

Options:
  -h  Show usage
  --address=[localhost]: Addresses to listen on (comma separated). Only accepts IP addresses or localhost as a value. When localhost is supplied, kubectl will try to bind on both 127.0.0.1 and ::1 and will fail if neither of these addresses are available to bind.
  --pod-running-timeout=1m0s: The length of time (like 5s, 2m, or 3h, higher than zero) to wait until at least one pod is running
EOF
  exit 0
}


[ $# -eq 0 ] && usage

KUBECTL="$(type -p kubectl)"
PORT_FORWARD_ARGS=""
EXEC_COMMAND=""
while true; do
  case "$1" in
    -h ) usage; exit 0 ;;
    -- ) shift; EXEC_COMMAND="$*"; break ;;
    * ) PORT_FORWARD_ARGS="$PORT_FORWARD_ARGS $1"; shift ;;
  esac
done

echo -e "port-forward with arguments ${PORT_FORWARD_ARGS}\nexecute command ${EXEC_COMMAND}"

# shellcheck disable=SC2086
${KUBECTL} port-forward ${PORT_FORWARD_ARGS} > /dev/null &
trap "kill -9 "$!" > /dev/null" EXIT

eval "${EXEC_COMMAND}"
